name = "infl-worker"
main = "worker/index.ts"
compatibility_flags = []

[env.production]
  kv_namespaces = [
    { binding = "PAGE_KV", id = "df984fdb34cf4546816e70f8e029b47a" },   # KV 바인딩
    { binding = "DB", id = "1bc18749-585b-4c55-b378-78a29af5b5ca" }      # D1 DB 바인딩
  ]

[[routes]]
  pattern = "https://infl-worker.loto09090909.workers.dev/*"   # 기본 제공되는 workers.dev 도메인
  zone_name = "loto09090909.workers.dev"   # 현재 Cloudflare 제공 도메인에 해당하는 zone_name 추가

