compatibility_date = "2025-12-14"
name = "infl-worker"
main = "worker/index.ts"
compatibility_flags = []

workers_dev = true  # workers.dev에서 실행되도록 설정

  kv_namespaces = [
    { binding = "PAGE_KV", id = "df984fdb34cf4546816e70f8e029b47a" },  # KV 설정 (PAGE_KV)
  ]
  d1_databases = [
    { binding = "DB", database_id = "1bc18749-585b-4c55-b378-78a29af5b5ca" }  # D1 DB 설정 (DB)
  ]

